# Generated by Django 4.2.7 on 2023-12-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkout_created_at_checkout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
