# Generated by Django 4.2.7 on 2023-12-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_dinosaur_video_url'),
        ('checkout', '0004_remove_checkout_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='checkout',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.checkout')),
                ('dinosaur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dinosaur')),
            ],
        ),
    ]
