# Generated by Django 4.2.7 on 2023-11-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinosaur',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
